apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-swarm
  name: argo-swarm
spec:
  selector:
    matchLabels:
      app: argo-swarm
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: argo-swarm
    spec:
      containers:
      - name: argo-swarm
        image: opsmx11/docker-swarm:9839424-592
